### ISSUE TITLE
Si units have spaces around them

### ISSUE THREAD

**Issue by feanor12** [Datax-package/Datax.sty#1]
If I use datax at the end of a sentence I get a space between the period and the value-unit pair. How do I avoid this?
using \SI{value}{unit} directly does not produce the space.

**Comment by gustaphe** [comment]
Thanks for the report! I'll look into this. A workaround in the meantime is to write `\( \datax{x} \)` (i.e. write it inside math mode).

**Comment by gustaphe** [comment]
What a silly mistake, thank you! I've submitted an update to CTAN.
