### ISSUE TITLE
Siunitx 

### ISSUE THREAD

**Issue by feanor12** [Datax-package/Datax.sty#2]
datax 1.1.2
siunitx 3.0.35
pgdkeyx 0.0.1

I think I get this since I use an updated  siunitx version
```

! LaTeX3 Error: The key 'siunitx/\pgfkeysvalueof
(LaTeX3) {/packageoptions/siunitxoptions}' is unknown and is being
(LaTeX3) ignored.
For immediate help type H <return>.
...
l.6 For the stress test, \datax{wavelength}
VCSEL arrays were used containin...
The module 'siunitx/\pgfkeysvalueof {/packageoptions' does not have a key
called 'siunitx/\pgfkeysvalueof {/packageoptions/siunitxoptions}'.
Check that you have spelled the key name correctly.
! LaTeX3 Error: The key 'siunitx/\pgfkeysvalueof
(LaTeX3) {/packageoptions/siunitxoptions}' is unknown and is being
(LaTeX3) ignored.
For immediate help type H <return>.
...
```

**Comment by gustaphe** [comment]
Thank you for reporting this! I rarely update my TeX setup so I wouldn't have noticed.

Somewhere along the way `sisetup` stopped expanding macros in its arguments, so
```tex
\newcommand{\option}{exponent-mode=scientific}
\sisetup{\option}
```
doesn't work anymore. I don't know if there's a way around it, but there was really no reason to use that hack anyway.

Should be closed with https://github.com/Datax-package/Datax.sty/commit/36456df8cd233b7aaf9a65caca9fa3b89c635fc5

(I've sent a patch to CTAN too, so it'll be updated there soon)
